rocketmq:
  nameServer: 192.168.100.1:9876
  # 生产者
  # 这些配置都是生产者的配置，不是消费者的
  producer:
    # 组名，规定在一个应用里面必须唯一
    group: retry-consumer-group
    # 同步消息发送失败重试次数
    retry-times-when-send-failed: 3
    # 异步消息发送失败重试的次数
    retry-times-when-send-async-failed: 3

  # 没鸟用
  consumer:
    repeat-times: 20